Model definition, train and eval
Not 100% working yet. The data needs to be accessed another way. I get:
TypeError: 'WindowsPath' object is not subscriptable